# Generated by Django 4.2.1 on 2023-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('katalog_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Wolna', 'Wolna'), ('Wypozyczona', 'Wypozyczona')], default='Wolna', max_length=20)),
            ],
        ),
    ]
