# Generated by Django 4.2.1 on 2023-06-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nazwisko')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcopies', to='ksiegozbior.book', verbose_name='Wybierz książkę')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, verbose_name='PESEL')),
                ('street', models.CharField(max_length=200, verbose_name='Ulica')),
                ('city', models.CharField(max_length=200, verbose_name='Miasto')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('house_number', models.CharField(max_length=20, verbose_name='Numer domu')),
                ('can_borrow', models.BooleanField(default=True, verbose_name='Czy może wypożyczać?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('receive_date', models.DateField()),
                ('book_copy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksiegozbior.bookcopy')),
                ('borrow_librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_borrow_librarian', to=settings.AUTH_USER_MODEL)),
                ('receive_librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_receive_librarian', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_librarian', to=settings.AUTH_USER_MODEL, verbose_name='Bibliotekarz wypożyczający')),
                ('receive_librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_librarian', to=settings.AUTH_USER_MODEL, verbose_name='Bibliotekarz odbierający')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wypożycz dla')),
            ],
        ),
    ]
