# Generated by Django 4.2.1 on 2023-06-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegozbior', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_librarian',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='receive_librarian',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='book_copy_id',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='borrow_librarian',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='receive_librarian',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookCopy',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
